- name: Jenkins setup
  hosts: server01
  become: yes
  tasks:
    - include: ../../defaults/tasks/java.yml

    - name: add jenkins repository
      apt_key:
        state: present
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key


    - name: Add jenkins repo
      apt_repository:
          filename: Jenkins
          repo: https://pkg.jenkins.io/debian-stable/
            

    - name: Install Jenkins
      package:
        name: jenkins
        state: present

    - name: Jenkins started and enable
      service:
        name: jenkins
        enabled: true
        state: started